### PR TITLE
Update readme (links, context, skeleton)

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
@hoangdat @Arsnael

**Comment by hoangdat** [comment]
I will update the sample code for:
- single method
- multiple methods
- session

**Comment by chibenwa** [comment]
Do you think we can merge it for now?

**Review by hoangdat — APPROVED** [review]

**Comment by Arsnael** [comment]
The point of tagging me if it's to merge before letting me the time to review?

**Pull request merged**
